approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: "7d"

npmPreapprovedPackages:
  - "nshm-*"
  - "nzshm-*"
  - "solvis-*"
  - "weka-*"
  - "toshi-*"

# npmScopes:
#   gns-science:
#     npmRegistryServer: "https://npm.pkg.github.com"
#     npmAuthToken: "${GITHUB_TOKEN}"
