name: Cypress Tests

on:
  push:
    branches:
      - main
      - deploy-test

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: create env file
        run: |
          touch .env
          echo VITE_MSW=test >> .env
          echo VITE_DISCLAIMER_VERSION=versionOne >> .env
          echo VITE_GRAPHQL_ENDPOINT=..../graphql >> .env
          echo VITE_GRAPHQL_API_KEY=$##@! >> .env
          echo GENERATE_SOURCEMAP=false >> .env
          cat .env

      - name: node and yarn
        uses: ./.github/actions/installYarn
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:5173
          record: true
          start: yarn run vite --host
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
