name: CD (ENV:TEST) build_test_push deploy-test into AWS nzshm22-kororaa-ui-test S3

on:
  push:
    branches: [ deploy-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS_TEST

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@gns-science'

      - name: Yarn Test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOSHI_NEST_PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Yarn build
        env:
          CI: false
        run: |
          echo "Configure build environment"
          touch .env
          echo "The following settings can be exposed, and are common to PROD and TEST.."
          echo "REACT_APP_HAZARD_COLOR_LIMIT=12" >> .env
          echo "REACT_APP_HAZARD_COLOR_MAP=portland" >> .env
          echo "REACT_APP_HAZARD_COLOR_UNCERTAINTY_OPACITY=0.8" >> .env
          echo "REACT_APP_GRID_ID=NZ_0_1_NB_1_0" >> .env
          echo "REACT_APP_MAP_IMTS=PGA,SA(0.1),SA(0.2),SA(0.5),SA(1.0),SA(1.5)" >> .env
          echo "REACT_APP_MAP_VS30S=250,400,750" >> .env
          echo "REACT_APP_MAP_STATISTICS=mean,0.8,0.9" >> .env
          echo "REACT_APP_MAP_POES=0.1,0.02" >> .env
          echo "REACT_APP_MAP_COLOR_SCALE=jet,inferno,viridis,plasma,magma,cividis" >> .env
          echo "REACT_APP_HAZARD_GMAX=5" >> .env
          echo "REACT_APP_HAZARD_GMIN=0" >> .env
          echo "REACT_APP_HAZARD_GMAX_LOG=5" >> .env
          echo "REACT_APP_HAZARD_GMIN_LOG=0.01" >> .env
          echo "REACT_APP_HAZARD_POEMAX=1" >> .env
          echo "REACT_APP_HAZARD_POEMIN=0.000001" >> .env
          echo "REACT_APP_SA_PERIODMAX=10" >> .env
          echo "REACT_APP_SA_PERIODMIN=0" >> .env
          echo "REACT_APP_SA_PERIODMAX_LOG=10" >> .env
          echo "REACT_APP_SA_PERIODMIN_LOG=0.01" >> .env
          echo "REACT_APP_SA_GMAX=auto" >> .env
          echo "REACT_APP_SA_GMIN=0" >> .env
          echo "REACT_APP_SA_LOG_PGA_SUBSTITUTE=0.02" >> .env
          echo
          cat .env
          echo "Now add the secrets.."
          echo "REACT_APP_DISCLAIMER_VERSION=${{secrets.REACT_APP_DISCLAIMER_VERSION}}" >> .env
          echo "REACT_APP_GRAPHQL_ENDPOINT=${{secrets.REACT_APP_GRAPHQL_ENDPOINT}}" >> .env
          echo "REACT_APP_GRAPHQL_API_KEY=${{secrets.REACT_APP_GRAPHQL_API_KEY}}" >> .env
          echo "REACT_APP_RESOLUTION=${{secrets.REACT_APP_RESOLUTION}}" >> .env
          echo "REACT_APP_HAZARD_MODEL=${{secrets.REACT_APP_HAZARD_MODEL}}" >> .env
          echo
          yarn build
    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          #The following are repository secrets 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          #The following are set up in AWS_TEST deployment environ        
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: "build"
