name: Deploy TEST

on:
  push:
    branches: [ deploy-test ]

jobs:
  call-deploy-workflow:
    runs-on: ubuntu-latest
    environment: AWS_TEST
    #https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/deploy_to_s3.yml
