name: Deploy PROD

on:
  push:
    branches: [ main ]

jobs:
  call-deploy-workflow:
    runs-on: ubuntu-latest
    environment: AWS_PROD
    #https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
    uses: ./.github/workflows/deploy-to-s3.yml