name: CD (ENV:TEST) build_test_push deploy-test into AWS nzshm22-kororaa-ui-test S3

on:
  push:
    branches: [ deploy-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS_TEST

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@gns-science'

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_DISCLAIMER_VERSION=${{ secrets.REACT_APP_DISCLAIMER_VERSION }} >> .env
          echo REACT_APP_GRAPHQL_ENDPOINT=${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }} >> .env
          echo REACT_APP_GRAPHQL_API_KEY=${{ secrets.REACT_APP_GRAPHQL_API_KEY}} >> .env
          echo REACT_APP_RESOLUTION=${{ secrets.REACT_APP_RESOLUTION}} >> .env
          echo REACT_APP_HAZARD_MODELN=${{ secrets.REACT_APP_HAZARD_MODEL}} >> .env

      - name: Yarn Build & Test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOSHI_NEST_PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false         
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          #The following are repository secrets 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          #The following are set up in AWS_TEST deployment environ        
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: "build"
